lema/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path("login/", views.login_page, name="login-page"),
    path("logout/", views.logout_page, name="logout-page"),
]

lema/administration/urls.py
from django.urls import path
from . import views

app_name = "administration"

urlpatterns = [
    path("", views.admin_home, name="admin-page"),
    path("accordion/", views.accordion, name="accordion-htmx"),
]

lema/client/urls.py
from django.urls import path
from . import views

app_name = "client"

urlpatterns = [
    path("", views.home, name="home"),
    path("galleria/", views.gallery, name="gallery"),
    path("appuntamento/", views.appointment_page, name="appointment-page"),
    path("calendar/", views.appointment_page_htmx, name="appointment-calendar"),
    path("day/<int:day>", views.day_htmx, name="day-htmx"),
    path("show-modal/", views.show_modal, name="show-modal"),
]

lema/lema/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("client.urls")),
    path("administration/", include("administration.urls")),
    # path("__reload__/", include("django_browser_reload.urls")),
] + static(settings.STATIC_URL)

lema/client/forms.py
from django import forms
from .models import (
    Eight,
    Eleven,
    Five,
    Four,
    HalfEight,
    HalfEleven,
    HalfFive,
    HalfFour,
    HalfNine,
    HalfTen,
    HalfThree,
    HalfTwo,
    Nine,
    Ten,
    Three,
    Two,
    UserInfo,
)
from django.conf import settings
from django.core.exceptions import ValidationError


class UserInfoForm(forms.ModelForm):
    class Meta:
        model = UserInfo
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(UserInfoForm, self).__init__(*args, **kwargs)
        self.fields["first_name"].required = False
        self.fields["last_name"].required = False
        self.fields["phone_number"].required = False

    def clean_first_name(self):
        first_name = self.cleaned_data["first_name"]

        if first_name == "" or first_name.isdigit():
            raise ValidationError("Inserici un nome valido!")
        return first_name

    def clean_last_name(self):
        last_name = self.cleaned_data["last_name"]

        if last_name == "" or last_name.isdigit():
            raise ValidationError("Inserici un cognome valido!")
        return last_name


class EightForm(forms.ModelForm):

    class Meta:
        model = Eight
        fields = [
            "user_info",
            "date",
        ]

    def clean(self):
        cleaned_data = super().clean()
        print(cleaned_data)
        date = cleaned_data.get("date")
        print(date)

        users = Eight.objects.filter(date=date).count()
        print(users)

        if users > settings.MAX_USERS:
            raise ValidationError("Maximum number of users exceeded.")

        return cleaned_data

    @property
    def time(self):
        return "8:00 - 8:30"


class HalfEightForm(forms.ModelForm):

    class Meta:
        model = HalfEight
        fields = [
            "user_info",
            "date",
        ]

    def clean(self):
        super().clean()
        date = self.cleaned_data.get("date")

        users = HalfEight.objects.filter(date=date).count()

        if users > settings.MAX_USERS:
            raise ValidationError("Maximum number of users exceeded.")

    @property
    def time(self):
        return "8:30 - 9:00"


class NineForm(forms.ModelForm):

    class Meta:
        model = Nine
        fields = [
            "user_info",
            "date",
        ]

    def clean(self):
        super().clean()
        date = self.cleaned_data.get("date")

        users = Nine.objects.filter(date=date).count()

        if users > settings.MAX_USERS:
            raise ValidationError("Maximum number of users exceeded.")

    @property
    def time(self):
        return "9:00 - 9:30"


class HalfNineForm(forms.ModelForm):

    class Meta:
        model = HalfNine
        fields = [
            "user_info",
            "date",
        ]

    def clean(self):
        super().clean()
        date = self.cleaned_data.get("date")

        users = HalfNine.objects.filter(date=date).count()

        if users > settings.MAX_USERS:
            raise ValidationError("Maximum number of users exceeded.")

    @property
    def time(self):
        return "9:30 - 10:00"


class TenForm(forms.ModelForm):

    class Meta:
        model = Ten
        fields = [
            "user_info",
            "date",
        ]

    def clean(self):
        super().clean()
        date = self.cleaned_data.get("date")

        users = Ten.objects.filter(date=date).count()

        if users > settings.MAX_USERS:
            raise ValidationError("Maximum number of users exceeded.")

    @property
    def time(self):
        return "10:00 - 10:30"


class HalfTenForm(forms.ModelForm):

    class Meta:
        model = HalfTen
        fields = [
            "user_info",
            "date",
        ]

    def clean(self):
        super().clean()
        date = self.cleaned_data.get("date")

        users = HalfTen.objects.filter(date=date).count()

        if users > settings.MAX_USERS:
            raise ValidationError("Maximum number of users exceeded.")

    @property
    def time(self):
        return "10:30 - 11:00"


class ElevenForm(forms.ModelForm):

    class Meta:
        model = Eleven
        fields = [
            "user_info",
            "date",
        ]

    def clean(self):
        super().clean()
        date = self.cleaned_data.get("date")

        users = Eleven.objects.filter(date=date).count()

        if users > settings.MAX_USERS:
            raise ValidationError("Maximum number of users exceeded.")

    @property
    def time(self):
        return "11:00 - 11:30"


class HalfElevenForm(forms.ModelForm):

    class Meta:
        model = HalfEleven
        fields = [
            "user_info",
            "date",
        ]

    def clean(self):
        super().clean()
        date = self.cleaned_data.get("date")

        users = HalfEleven.objects.filter(date=date).count()

        if users > settings.MAX_USERS:
            raise ValidationError("Maximum number of users exceeded.")

    @property
    def time(self):
        return "11:30 - 12:00"


class TwoForm(forms.ModelForm):

    class Meta:
        model = Two
        fields = [
            "user_info",
            "date",
        ]

    def clean(self):
        super().clean()
        date = self.cleaned_data.get("date")

        users = Two.objects.filter(date=date).count()

        if users > settings.MAX_USERS:
            raise ValidationError("Maximum number of users exceeded.")

    @property
    def time(self):
        return "14:00 - 14:30"


class HalfTwoForm(forms.ModelForm):

    class Meta:
        model = HalfTwo
        fields = [
            "user_info",
            "date",
        ]

    def clean(self):
        super().clean()
        date = self.cleaned_data.get("date")

        users = HalfTwo.objects.filter(date=date).count()

        if users > settings.MAX_USERS:
            raise ValidationError("Maximum number of users exceeded.")

    @property
    def time(self):
        return "14:30 - 15:00"


class ThreeForm(forms.ModelForm):

    class Meta:
        model = Three
        fields = [
            "user_info",
            "date",
        ]

    def clean(self):
        super().clean()
        date = self.cleaned_data.get("date")

        users = Three.objects.filter(date=date).count()

        if users > settings.MAX_USERS:
            raise ValidationError("Maximum number of users exceeded.")

    @property
    def time(self):
        return "15:00 - 15:30"


class HalfThreeForm(forms.ModelForm):

    class Meta:
        model = HalfThree
        fields = [
            "user_info",
            "date",
        ]

    def clean(self):
        super().clean()
        date = self.cleaned_data.get("date")

        users = HalfThree.objects.filter(date=date).count()

        if users > settings.MAX_USERS:
            raise ValidationError("Maximum number of users exceeded.")

    @property
    def time(self):
        return "15:30 - 16:00"


class FourForm(forms.ModelForm):

    class Meta:
        model = Four
        fields = [
            "user_info",
            "date",
        ]

    def clean(self):
        super().clean()
        date = self.cleaned_data.get("date")

        users = Four.objects.filter(date=date).count()

        if users > settings.MAX_USERS:
            raise ValidationError("Maximum number of users exceeded.")

    @property
    def time(self):
        return "16:00 - 16:30"


class HalfFourForm(forms.ModelForm):

    class Meta:
        model = HalfFour
        fields = [
            "user_info",
            "date",
        ]

    def clean(self):
        super().clean()
        date = self.cleaned_data.get("date")

        users = HalfFour.objects.filter(date=date).count()

        if users > settings.MAX_USERS:
            raise ValidationError("Maximum number of users exceeded.")

    @property
    def time(self):
        return "16:30 - 17:00"


class FiveForm(forms.ModelForm):

    class Meta:
        model = Five
        fields = [
            "user_info",
            "date",
        ]

    def clean(self):
        super().clean()
        date = self.cleaned_data.get("date")

        users = Five.objects.filter(date=date).count()

        if users > settings.MAX_USERS:
            raise ValidationError("Maximum number of users exceeded.")

    @property
    def time(self):
        return "17:00 - 17:30"


class HalfFiveForm(forms.ModelForm):

    class Meta:
        model = HalfFive
        fields = [
            "user_info",
            "date",
        ]

    def clean(self):
        super().clean()
        date = self.cleaned_data.get("date")

        users = HalfFive.objects.filter(date=date).count()
        print(users)

        if users > settings.MAX_USERS:
            raise ValidationError("Maximum number of users exceeded.")

    @property
    def time(self):
        return "17:30 - 18:00"

lema/client/views.py
from urllib.parse import urlencode
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.contrib import messages
from django.conf import settings
from django.http import QueryDict
from sms import send_sms
from decouple import config

from .calendar_view import Custom2HTMLCalendar
from datetime import date as dt

from .forms import *

from .forms import UserInfoForm


def home(request):
    context = {
        "full_star": config("FULL_STAR"),
        "outline_star": config("OUTLINE_STAR"),
        "image_1": config("IMAGE_1"),
        "image_2": config("IMAGE_2"),
        "image_3": config("IMAGE_3"),
        "home_img": config("HOME_IMG"),
    }
    view = render(request, "home.html", context)
    return view


def gallery(request):
    context = {
        "tagli": [
            config("TAGLIO_1"),
            config("TAGLIO_2"),
            config("TAGLIO_3"),
            config("TAGLIO_4"),
            config("TAGLIO_5"),
            config("TAGLIO_6"),
            config("TAGLIO_7"),
            config("TAGLIO_8"),
            config("TAGLIO_9"),
            config("TAGLIO_10"),
            config("TAGLIO_11"),
            config("TAGLIO_12"),
            config("TAGLIO_13"),
            config("TAGLIO_14"),
            config("TAGLIO_15"),
            config("TAGLIO_16"),
            config("TAGLIO_17"),
            config("TAGLIO_18"),
            config("TAGLIO_19"),
            config("TAGLIO_20"),
            config("TAGLIO_21"),
            config("TAGLIO_22"),
            config("TAGLIO_23"),
            config("TAGLIO_24"),
        ]
    }
    view = render(request, "gallery.html", context)
    return view


def appointment_page(request):
    context = {}
    request.session["set_month"] = dt.today().month
    request.session["set_year"] = dt.today().year

    cal = Custom2HTMLCalendar().formatmonth(
        request.session["set_year"], request.session["set_month"]
    )
    context["cal"] = cal
    context["booking_appoints_url"] = config("BOOKING_APPOINTS_URL")
    view = render(request, "appointment_page.html", context)

    return view


def appointment_page_htmx(request):
    context = {}

    if request.method == "POST":
        print(request.POST)
        arrow = request.POST.get("arrow")

        if arrow == "right":
            if request.session["set_month"] + 1 > 12:
                request.session["set_month"] = 1
                request.session["set_year"] += 1
            else:
                request.session["set_month"] += 1

        elif arrow == "left":
            if request.session["set_month"] - 1 < 1:
                request.session["set_month"] = 12
                request.session["set_year"] -= 1
            else:
                request.session["set_month"] -= 1

        elif arrow == "current_day":
            request.session["set_month"] = dt.today().month
            request.session["set_year"] = dt.today().year

    request.session["set_year"], request.session["set_month"]

    cal = Custom2HTMLCalendar().formatmonth(
        request.session["set_year"], request.session["set_month"]
    )

    context["cal"] = cal
    view = render(request, "partials/appointment_calendar.html", context)

    return view


def day_htmx(request, day):
    context = {
        "options": [
            EightForm(),
            HalfEightForm(),
            NineForm(),
            HalfNineForm(),
            TenForm(),
            HalfTenForm(),
            ElevenForm(),
            HalfElevenForm(),
            TwoForm(),
            HalfTwoForm(),
            ThreeForm(),
            HalfThreeForm(),
            FourForm(),
            HalfFourForm(),
            FiveForm(),
            HalfFiveForm(),
        ],
        "day": day,
        "max_users": settings.MAX_USERS,
    }

    view = render(request, "partials/available_option.html", context)

    return view


def show_modal(request):
    request.session["set_day"] = request.POST.get("day")
    request.session["time_selection"] = request.POST.get("selection")
    day = request.session["set_day"]
    month = request.session["set_month"]
    year = request.session["set_year"]

    print(request.session["time_selection"])

    context = {
        "user_form": UserInfoForm(),
        "time": request.session["time_selection"],
        "day": request.session["set_day"],
        "month": request.session["set_month"],
        "year": request.session["set_year"],
    }

    form_options = [
        EightForm,
        HalfEightForm,
        NineForm,
        HalfNineForm,
        TenForm,
        HalfTenForm,
        ElevenForm,
        HalfElevenForm,
        TwoForm,
        HalfTwoForm,
        ThreeForm,
        HalfThreeForm,
        FourForm,
        HalfFourForm,
        FiveForm,
        HalfFiveForm,
    ]

    if request.method == "POST" and request.POST.get("type") == "submit":
        user_info = UserInfoForm(request.POST)
        phone_number = request.POST.get("phone_number")
        print(phone_number)

        if user_info.is_valid():
            user = UserInfo.objects.get(phone_number=phone_number)

            if not user:
                user = user_info.save()

            for form_class in form_options:

                if form_class().time == request.session["time_selection"]:

                    date = f"{year}-{month}-{day}"
                    dictionary = {"user_info": user.pk, "date": date}
                    q_dictionary = QueryDict(
                        urlencode(dictionary, doseq=True), mutable=True
                    )
                    form = form_class(q_dictionary)

                    if form.is_valid():
                        print("valida")
                        form.save()
                        print("salvato")
                        messages.success(request, "Prenotazione salvata con successo!")
                    else:
                        messages.warning(request, form.errors)

        else:
            context["user_form"] = user_info
            context["errors"] = user_info.errors

        view = render(request, "partials/show-modal.html", context)
        return view

    return render(request, "partials/show-modal.html", context)

lema/client/templates/appointment_page.html
{% extends "base.html" %}
{% block title %}Appuntamento{% endblock %}

{% block content %}

{% load static %}
{% load static tailwind_tags %}


<div class="flex sm:flex-row flex-col py-8">
{{cal|safe|escape}}
  <div class="flex flex-col">
    <div class="flex flex-col items-center justify-start mt-12 sm:mt-4 font-bold" >
      <section id="message-alert">
      </section>
      <p class="text-xl">Scegli uno tra i seguenti orari disponibili:</p>
      <div id="timetable">
        <select class="select select-bordered w-full max-w-xs">
          <option disabled selected>----</option>
        </select>
      </div>
    </div>
    <div class="flex flex-auto items-end">
      <img src="{{booking_appoints_url}}" alt="Img" width="400" class="hidden sm:block">
    </div>
  </div>
</div>

<dialog id="my_modal" class="modal">
  <div class="modal-box" id="custom-modal-box"></div>
</dialog>


{% endblock content %}

lema/client/templates/base.html
{% load static %}
{% load static tailwind_tags %}

<!DOCTYPE html>
<html lang="en" data-theme="light">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Lema - {% block title %}{% endblock title %}</title>
    {% tailwind_css %}
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800&display=swap"
      rel="stylesheet"
    />
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.28.0/feather.min.js"
      integrity="sha512-7x3zila4t2qNycrtZ31HO0NnJr8kg2VI67YLoRSyi9hGhRN66FHYWr7Axa9Y1J9tGYHVBPqIjSE1ogHrJTz51g=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    ></script>
    <script src="https://unpkg.com/htmx.org@2.0.0" integrity="sha384-wS5l5IKJBvK6sPTKa2WZ1js3d947pvWXbPJ1OmWfEuxLgeHcEbjUUA5i9V5ZkpCw" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/alpinejs@3.14.1/dist/cdn.min.js"></script>

  </head>

  <body class="bg-white" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>


    <section class="py-2 md:py-4">
      <div class="container max-w-screen-xl mx-auto px-4">
        <nav
          class="flex-wrap lg:flex items-center justify-between mb-5 lg:mb-10"
          x-data="{navbarOpen:false}"
        >
          <div class="flex items-center justify-between mb-10 lg:mb-0">
            <img
              src="https://ubisagpcdrzyseljfocd.supabase.co/storage/v1/object/sign/static/images/navbar_logo.png?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJzdGF0aWMvaW1hZ2VzL25hdmJhcl9sb2dvLnBuZyIsImlhdCI6MTcyMDUzMjM3NSwiZXhwIjozMzI1NjUzMjM3NX0.2K4aKy7RvfhiCAEQU1EjbqJiPsVD5b3H3Y0zMzMVhjQ&t=2024-07-09T13%3A39%3A35.544Z"
              alt="Logo"
              width="91"
              height="91"
            />
    
            <button
              class="flex items-center justify-center border border-green-500 w-10 h-10 text-green-500 rounded-md outline-none lg:hidden ml-auto"
              @click="navbarOpen = !navbarOpen"
            >
               <img src="https://ubisagpcdrzyseljfocd.supabase.co/storage/v1/object/sign/static/images/menu_logo.svg?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1cmwiOiJzdGF0aWMvaW1hZ2VzL21lbnVfbG9nby5zdmciLCJpYXQiOjE3MjA1MzI0MzYsImV4cCI6MzMyNTY1MzI0MzZ9.5h2R3-y5o0tyxKiSx_5pXOz4hRmOe-8bXUSlcEYFg3o&t=2024-07-09T13%3A40%3A36.165Z" alt="">
            </button>
          </div>
    
          <ul
            class="hidden lg:block lg:flex flex-col lg:flex-row lg:items-center lg:space-x-20"
            :class="{'hidden':!navbarOpen,'flex':navbarOpen}"
          >
            <li
              class="font-medium text-green-500 text-lg hover:text-green-300 transition ease-in-out duration-300 mb-5 lg:mb-0"
            >
              <a href='{% url "client:home" %}'>Home</a>
            </li>

            {% if request.user.is_authenticated %}
            <li
              class="font-medium text-green-500 text-lg hover:text-green-300 transition ease-in-out duration-300 mb-5 lg:mb-0"
            >
              <a href='{% url "accounts:logout-page" %}'>Logout</a>
            </li>
            {% endif %}
    
            <li
              class="font-medium text-green-500 text-lg hover:text-green-300 transition ease-in-out duration-300 mb-5 lg:mb-0"
            >
            {% if request.user.is_authenticated %}
              <a href="{% url 'administration:admin-page' %}">Administration</a>
            {% else %}
              <a href="{% url 'accounts:login-page' %}">Login</a>
            {% endif %}
            </li>
    
            <li
              class="px-8 py-3 font-medium text-green-500 text-lg text-center border-2 border-green-500 rounded-md hover:bg-green-500 hover:text-white transition ease-linear duration-300"
            >
              <a href="{% url 'client:gallery' %}">La nostra galleria</a>
            </li>
          </ul>
        </nav>
      </div>
    </section>
    {% block content %}{% endblock content %}
    {% block scripts %}{% endblock scripts %}
  </body>
</html>

lema/client/templates/gallery.html
{% extends "base.html" %}

{% block title %}Galleria{% endblock title %}

{% block content %}
<section class="py-8 md:py-16">
  <div class="container max-w-screen-xl mx-auto px-4">
    <h1
      class="font-semibold text-gray-700 text-3xl md:text-4xl text-center mb-20"
    >
      Il nostro lavoro
    </h1>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-5 xl:gap-10">
      {% for img in tagli %}
      <div class="space-y-2 xl:space-y-4">
        <img
          src="{{img}}"
          alt="Image"
          class="hover:opacity-75 transition ease-in-out duration-300 rounded-md"
        />
      </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock content %}

lema/client/templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock title %}

{% block content %}

{% load static %}

<!-- feature section -->
<section class="py-4 md:py-8">
  <header class="flex-col xl:flex-row flex justify-between">
    <div
      class="mx-auto text-center xl:text-left xl:mx-0 mb-20 xl:mb-0 pl-2 md:pl-14"
    >
      <h1
        class="font-bold text-gray-700 text-3xl md:text-6xl leading-tight mb-10"
      >
        LEMA Parrucchieri <br />
        Levratti & Malaguti <br />
      </h1>

      <p class="font-normal text-gray-500 text-sm md:text-lg mb-10">
        Scopri l'arte delle acconciature con i nostri consigli <br />
        e ispirazioni per ogni occasione!
      </p>

      <div class="pl-14 flex items-center justify-center lg:justify-start">
        <a
          href='{% url "client:appointment-page" %}'
          class="px-12 py-3 bg-green-500 font-medium text-white text-md md:text-lg rounded-md hover:bg-green-700 transition ease-in-out duration-300 mr-14"
          >Prendi un appuntamento</a
        >
      </div>
    </div>

    <div class="mx-auto xl:mx-0">
      <img src='{{home_img}}' alt="Image" />
    </div>
  </header>

  <div class="container max-w-screen-xl mx-auto px-4 mt-10">
    <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3">
      <div class="text-center mb-10 xl:mb-0">
        <div class="flex items-center justify-center">
          <div
            class="w-20 py-7 flex justify-center bg-purple-50 text-purple-500 rounded-md mb-5 md:mb-10"
          >
            <i data-feather="search"></i>
          </div>
        </div>

        <h2 class="font-semibold text-gray-700 text-xl md:text-3xl mb-5">
          Cura nel dettagio
        </h2>

        <p class="font-normal text-gray-400 text-sm md:text-lg">
          "Dedichiamo attenzione ai dettagli <br />
          per garantire risultati impeccabili <br />
          e soddisfare ogni esigenza."
        </p>
      </div>

      <div class="text-center mb-10 md:mb-0">
        <div class="flex items-center justify-center">
          <div
            class="w-20 py-7 flex justify-center bg-red-50 text-red-500 rounded-md mb-5 md:mb-10"
          >
            <i data-feather="sliders"></i>
          </div>
        </div>

        <h2 class="font-semibold text-gray-700 text-xl md:text-3xl mb-5">
          Stile Personalizzato
        </h2>

        <p class="font-normal text-gray-400 text-sm md:text-lg">
          "Creiamo stili unici e personalizzati <br />
          che esaltano la bellezza naturale di ogni cliente."
        </p>
      </div>

      <div class="text-center">
        <div class="flex items-center justify-center">
          <div
            class="w-20 py-7 flex justify-center bg-blue-50 text-blue-500 rounded-md mb-5 md:mb-10"
          >
            <i data-feather="droplet"></i>
          </div>
        </div>

        <h2 class="font-semibold text-gray-700 text-xl md:text-3xl mb-5">
          Benessere Capelli
        </h2>

        <p class="font-normal text-gray-400 text-sm md:text-lg">
          "Promuoviamo il benessere dei capelli <br />
          con trattamenti innovativi <br />
          e prodotti di alta qualità."
        </p>
      </div>
    </div>
  </div>
</section>
<!-- feature section //end -->

<section class="py-8 md:py-16">
  <div class="container max-w-screen-xl mx-auto px-4">
    <h1
      class="font-semibold text-gray-700 text-3xl md:text-4xl text-center mb-20 md:mb-40"
    >
      Alcune delle recensioni...
    </h1>

    <div class="container m-auto px-6 pb-6 md:px-12 xl:px-0 font-mono">
      <div class="mx-auto grid gap-6 md:w-3/4 lg:w-full lg:grid-cols-3">
        <div class="bg-white rounded-2xl shadow-xl px-8 py-12 sm:px-12 lg:px-8">
          <div class="mb-12 space-y-4">
            <h3 class="text-2xl font-semibold text-[#284B63]">
              Spino2100
              <div class="flex flex-row mt-4">
                <img src="{{full_star}}" alt="" />
                <img src="{{full_star}}" alt="" />
                <img src="{{full_star}}" alt="" />
                <img src="{{full_star}}" alt="" />
                <img src="{{full_star}}" alt="" />
              </div>
            </h3>
            <p class="mb-6">
              Salone molto bello e accogliente ! Personale gentile e
              professionale ! Consigliatissimi !
            </p>
            <a
              href="https://maps.app.goo.gl/vnJUt9suLbGcNZhd8"
              class="block font-medium text-sky-700"
              >Vieni a trovarci!</a
            >
          </div>
          <img
            src="{{image_2}}"
            class="w-2/3 ml-auto -mb-12"
            alt="illustration"
            loading="lazy"
            width="650"
            height="350"
          />
        </div>
        <div
          class="bg-white rounded-2xl shadow-2xl px-8 py-12 sm:px-12 lg:px-8"
        >
          <div class="mb-12 space-y-4">
            <h3 class="text-2xl font-semibold text-[#284B63]">
              Mattia Cestari
              <div class="flex flex-row mt-4">
                <img src="{{full_star}}" alt="" />
                <img src="{{full_star}}" alt="" />
                <img src="{{full_star}}" alt="" />
                <img src="{{full_star}}" alt="" />
                <img src="{{outline_star}}" alt="" />
              </div>
            </h3>
            <p class="mb-6">
              Servizio impeccabile, ambiente impeccabile, serietà e
              professionalità
            </p>
            <a
              href="https://maps.app.goo.gl/vnJUt9suLbGcNZhd8"
              class="block font-medium text-[#153243]"
              >Vieni a trovarci!</a
            >
          </div>
          <img
            src="{{image_1}}"
            class="w-2/3 ml-auto"
            alt="illustration"
            loading="lazy"
            width="650"
            height="350"
          />
        </div>
        <div class="bg-white rounded-2xl shadow-xl px-8 py-12 sm:px-12 lg:px-8">
          <div class="mb-12 space-y-4">
            <h3 class="text-2xl font-semibold text-[#284B63]">
              Enrica Ruosi
              <div class="flex flex-row mt-4">
                <img src="{{full_star}}" alt="" />
                <img src="{{full_star}}" alt="" />
                <img src="{{full_star}}" alt="" />
                <img src="{{full_star}}" alt="" />
                <img src="{{full_star}}" alt="" />
              </div>
            </h3>
            <p class="mb-6">
              Ottima scoperta!! Professionalità e cura al primo posto!!
              Consigliatisssssssssimo
            </p>
            <a
              href="https://maps.app.goo.gl/vnJUt9suLbGcNZhd8"
              class="block font-medium text-[#153243]"
              >Vieni a trovarci!</a
            >
          </div>
          <img
            src="{{image_3}}"
            class="w-2/3 ml-auto"
            alt="illustration"
            loading="lazy"
            width="650"
            height="350"
          />
        </div>
      </div>
    </div>
  </div>
</section>

<script>
  feather.replace();
</script>
{% endblock content %}